import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, ManyToOne, JoinColumn, OneToMany } from 'typeorm';
import { InvitationCode } from './InvitationCode';

@Entity('users')
export class User {
    @PrimaryGeneratedColumn()
    id: number;

    @Column({ type: 'bigint', unique: true })
    telegram_id: number;

    @Column({ type: 'text', nullable: true })
    username: string;

    @Column({ type: 'boolean', default: false })
    has_used_trial: boolean = false;

    @Column({ type: 'boolean', default: true })
    is_active: boolean = true;

    @CreateDateColumn()
    created_at: Date;

    // Tracking who invited this user
    @ManyToOne(() => User, (user) => user.invitees, { nullable: true })
    @JoinColumn({ name: 'invited_by_user_id' })
    invited_by: User;

    @Column({ nullable: true })
    invited_by_user_id: number;

    // The users that THIS user has invited
    @OneToMany(() => User, (user) => user.invited_by)
    invitees: User[];

    // The invitation codes generated by this admin/user
    @OneToMany(() => InvitationCode, (code) => code.creator)
    codes_created: InvitationCode[];
}
